**Import Libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

*  numpy is imported for numerical operations.
*  matplotlib.pyplot is imported for plotting, though it is not used in the given code.

**Define the Positional Encoding Function**

In [2]:
def get_position_encoding(seq_len, d, n = 10000):
  p = np.zeros((seq_len, d))
  for k in range(seq_len):
    for i in np.arange(int(d/2)):
      denominator = np.power(n, 2*i/d)
      p[k, 2*i] = np.sin(k/denominator)
      p[k, 2*i+1] = np.cos(k/denominator)
  return p

*  Function Signature: The function get_position_encoding takes three arguments:

   *  seq_len: Length of the sequence.
   *  d: Dimensionality of the encoding.
   *  n: A scaling factor for the position (default is 10000).
*  Initialize Matrix: p = np.zeros((seq_len, d))

   *  Initializes a zero matrix p with shape (seq_len, d) to hold the positional encodings.
*  Loop Over Sequence Length: for k in range(seq_len):

   *  Iterates over each position k in the sequence.
*  Loop Over Half the Dimensionality: for i in np.arange(int(d/2)):

   *  Iterates over half the dimensions (d/2) because each position uses both sine and cosine values for even and odd indices.
*  Calculate Denominator: denominator = np.power(n, 2*i/d)

   *  Calculates the denominator for the sine and cosine functions.
*  Assign Sine Values: p[k, 2*i] = np.sin(k/denominator)

   *  Assigns the sine value to the even index of the k-th position.
*  Assign Cosine Values: p[k, 2*i+1] = np.cos(k/denominator)

   *  Assigns the cosine value to the odd index of the k-th position.
*  Return Encoding Matrix: return p

   *  Returns the positional encoding matrix p.

**Generate Positional Encodings**

In [3]:
p = get_position_encoding(seq_len = 4, d = 4, n = 100)
print(p)

[[ 0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.09983342  0.99500417]
 [ 0.90929743 -0.41614684  0.19866933  0.98006658]
 [ 0.14112001 -0.9899925   0.29552021  0.95533649]]


*  Calls the get_position_encoding function with a sequence length of 4, dimensionality of 4, and n value of 100.
*  Prints the resulting positional encoding matrix p.

**Summary**<br>
This code defines a function to generate positional encodings, which are used to provide information about the position of each token in a sequence to transformer models. The positional encodings are calculated using sine and cosine functions with varying frequencies.